export const environment = {
  production: false,
  logintr: 'https://stg.registro.solucionesbolivarsites.com/javascripts/basic-login-system-stg.js',
  logintrenv: "stgbolivarconmigo",
  blogUrl: "https://www.segurosbolivar.com/blog/",
  blogApiTerms: "https://sw732y54ee.execute-api.us-east-1.amazonaws.com/stage/bienestar/BlogAndTerms/getBienestarBlogApiTerms",
  blogApiPolicies: "https://sw732y54ee.execute-api.us-east-1.amazonaws.com/stage/bienestar/BlogAndTerms/getBienestarBlogApiPolicies",
  helpEmail: "segurosbolivarapp@segurosbolivar.com",
  callHelpNumber: "#322",
  whatsappHelpClientNumber: "+573223322322",
  whatsappHelpNumber: "+573124852995",
  callEmergencyNationalNumber: "123",
  bienestarUrlApi: "https://sw732y54ee.execute-api.us-east-1.amazonaws.com/stage",
  googleAnalytics: "UA-179616620-2",
  base64EncodedKeyFromJava: 'QUJDREVGR0hJSktMTU5PUA==',
  qrenv: 'stg',
  surveyUrl:"https://bienestar-dev-bienestar-webresources.s3.amazonaws.com/survey.html",
};